Latest Yoga
Mokosha/yoga-hs pull request #5
Opened 2021-05-02 18:35 UTC by aktowns

Hiya!

I took a shot at the first two points of #4 :smile:, yoga is now a submodule and i updated the bindings to match the changes. I had to use a C wrapper for some functions as it seems haskells FFI doesn't support returning structures by value, I added tests for the wrapper functions. The only changes i made to the high level wrapper was so it still worked with the bindings changes.

2021-06-03 02:46 UTC, Mokosha requested changes
Wow, what a pleasant surprise. Thank you so much!! Just a minor comment about the SSH path for the URL and I think it's good to go (provided the tests pass!).

2021-06-03 02:46 UTC, Mokosha commented on .gitmodules
> +	url = git@github.com:facebook/yoga.git
Please use `https://github.com/facebook/yoga.git` as the git URL so that we have to have github get feisty with SSH permissions.

2021-06-03 02:46 UTC, Mokosha commented on test/Bindings/YogaSpec.hs
> +module Bindings.YogaSpec where
Awesome!! Thank you!!

2021-06-04 08:08 UTC, merged

2021-06-04 08:08 UTC, Mokosha commented
Thanks!! I think there's still some work to do with cleaning up travis, but this is great so far.

2021-06-05 10:04 UTC, aktowns commented
Heya! 
Sorry started looking into why travis was breaking yesterday but got distracted 
I've only tested on 8.10.x on linux wondering if maybe i've inadvertently broken it for older ghc versions :disappointed: 

I'm also a bit confused to why its not finding 
```
<command line>: does not exist: yoga/yoga/Utils.cpp
```

as it seems to be checking out the submodule fine